- name: Create LDAP Server instance
  hosts: localhost
  gather_facts: False
  vars_files:
  - ec2_env_vars
  tasks:
    - name: Launch instance
      ec2:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"     
        key_name: "{{ key_name }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        count: 2
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
      register: ec2_output

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2_output.instances }}"

    - name: Add new instance to host group
      add_host: #hostname={{ item.public_ip }} groups=servers
        hostname: "{{ item.public_ip }}"
        groupname: servers
      with_items: "{{ ec2_output.instances }}"

      #    - local_action:
      #        module: copy
      #        content: "{{ ec2_output.stdout |to_nice_yaml }}"
      #        dest: "/tmp/ec2-info.yml"
